try:
    a = int(input("enter a number: "))
    print(a)
except Exception as e:
    print(e)
print("Thankyou")



# try:
#     a = int(input("enter a number: "))
#     print(a)
# except ValueError as v:
#     print("ValueError occurred")
#     print(v)
# except Exception as e:
#     print(e)
# print("Thankyou")



# a = int(input("enter a number: "))
# print("Thankyou")